apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
{{ include "ntfy.labels" . | indent 4 }}
data:
  server.yml: |
    base-url: {{ .Values.server.baseUrl | quote }}
    listen-http: ":8080"
    behind-proxy: {{ .Values.server.behindProxy }}

    # iOS instant push
    upstream-base-url: {{ .Values.server.upstreamBaseUrl | quote }}

    # Cache
    cache-duration: {{ .Values.server.cacheDuration | quote }}

    {{- if and (not .Values.databaseSecret) .Values.server.databaseUrl }}
    database-url: {{ .Values.server.databaseUrl | quote }}
    {{- end }}

    # Auth
    auth-default-access: {{ .Values.server.authDefaultAccess | quote }}
    enable-signup: {{ .Values.server.enableSignup }}
    enable-login: {{ .Values.server.enableLogin }}
    web-root: {{ .Values.server.webRoot | default "/" | quote }}

    # Rate limiting
    visitor-subscription-limit: {{ .Values.server.visitorSubscriptionLimit }}
    visitor-request-limit-burst: {{ .Values.server.visitorRequestLimitBurst }}
    visitor-request-limit-replenish: {{ .Values.server.visitorRequestLimitReplenish | quote }}
    visitor-message-daily-limit: {{ .Values.server.visitorMessageDailyLimit }}

    # Messages
    message-size-limit: {{ .Values.server.messageSizeLimit | quote }}
    message-delay-limit: {{ .Values.server.messageDelayLimit | quote }}

    # Attachments
    attachment-cache-dir: "/var/cache/ntfy/attachments"
    attachment-file-size-limit: {{ .Values.server.attachmentFileSizeLimit | quote }}
    attachment-total-size-limit: {{ .Values.server.attachmentTotalSizeLimit | quote }}
    attachment-expiry-duration: {{ .Values.server.attachmentExpiryDuration | quote }}

    # Keepalive
    keepalive-interval: {{ .Values.server.keepaliveInterval | quote }}

    # Logging
    log-level: {{ .Values.server.logLevel | quote }}
    log-format: {{ .Values.server.logFormat | quote }}
