{{- if .Values.externalRouting.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "web-service.fullname" . }}-external
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.externalRouting.gateway.name }}
      namespace: {{ .Values.externalRouting.gateway.namespace }}
  hostnames:
    - {{ .Values.externalRouting.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: {{ include "web-service.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.service.port }}
{{- end }}