server:
  baseUrl: "https://ping.tat.systems"

credentialsSecret: ntfy-credentials

users:
  - name: cluster
    passwordKey: cluster-password
    role: user
    access:
      - topic: "*"
        permission: wo
  - name: mobile
    passwordKey: mobile-password
    role: user
    access:
      - topic: "*"
        permission: ro

externalRouting:
  enabled: true
  hostname: "ping.tat.systems"
  gateway:
    name: istio-gateway
    namespace: istio-gateway
