server:
  baseUrl: "https://ping.tat.systems"

databaseSecret: ntfy-db-credentials

externalRouting:
  enabled: true
  hostname: "ping.tat.systems"
  gateway:
    name: istio-gateway
    namespace: istio-gateway
