# Default values for external-web-service

image:
  repository: nginx
  tag: "alpine"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

routing:
  hostname: example.com
  gateway:
    name: external-gateway
    namespace: istio-system

nodeSelector: {}
tolerations: []
affinity: {}