{{- if .Values.externalGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.externalGateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.externalGateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.externalGateway.http.port }}
      hostname: {{ .Values.externalGateway.http.hostname | quote }}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                {{- range .Values.externalGateway.http.allowedRoutes.namespaces }}
                  - {{ . }}
                {{- end }}
        kinds:
          - group: gateway.networking.k8s.io
            kind: HTTPRoute
{{- end }}