{{- if .Values.externalGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalGateway.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.externalGateway.name }}
    istio: gateway
  type: LoadBalancer
  selector:
    istio: gateway
    app: {{ .Values.externalGateway.name }}
  ports:
  - name: http
    port: {{ .Values.externalGateway.http.port }}
    targetPort: {{ .Values.externalGateway.http.port }}
    protocol: TCP
  {{- if .Values.externalGateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.externalGateway.service.loadBalancerIP }}
  {{- end }}
{{- end }}